### ISSUE TITLE
Unable to find "index.js"

### ISSUE THREAD

**Issue by LittleChest** [MrMicky-FR/CraftStats#1]
[ERROR] The expected output file at "index.js" was not found after running custom build: npm install && npm run build.

   The `main` property in wrangler.toml should point to
   the file generated by the custom build.

what should I do?

**Comment by MrMicky-FR** [comment]
Hi, in the `wrangler.toml` file, can you try to replace the following lines:
https://github.com/MrMicky-FR/CraftStats/blob/4ed704cca0aad72f614e1b468d492b632272e5c0/wrangler.example.toml#L1-L6

With these lines:
```toml
name = "craftstats"
account_id = ""
workers_dev = true
compatibility_date = "2022-06-05"
main = "./src/index.ts"
```

And then remove this line:
https://github.com/MrMicky-FR/CraftStats/blob/4ed704cca0aad72f614e1b468d492b632272e5c0/wrangler.example.toml#L41

I'll update the project to use [JavaScript modules](https://blog.cloudflare.com/workers-javascript-modules/) which should be a lot cleaner and easier to deploy 😃
